version: '3'
services:
  api-service:
    container_name: api-service
    build:
      context: .
      dockerfile: Dockerfile
    command: 'yarn start:debug'
    restart: always
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./:/app
      - '/app/node_modules'
